### PR TITLE
Ks/authorization v2

### PR DESCRIPTION
**Pull request by ks10825n**
Hey guys,

I think the basic authorization route is set up. React router will automatically kick you to login page if you don't have a valid session in your browser. Login and Signup should work as well. I put in a logout feature within the header also.

### CODE REVIEW

**Comment by ks10825n** [comment]
I added a commit for adding our bundle.js into gitignore. Don't think we need the bundle in our repo since webpack will build it out locally. It'll prevent merge conflicts as well.

**Review by maraquepo — APPROVED** [review]
LGTM! I already have the MUI styling ready whenever you merge.

**Comment by brynrmrzz** [comment]
@ks10825n  I would just delete your package-lock. Probably would be best to include it in your .gitignore.

**Review by anerolabs — APPROVED** [review]
Looks really good and clean Kevin. Nice job.

**Pull request merged**
